# -*- coding: utf-8 -*-
"""day2 100 days of python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F7MbtiC1Le2mfWCBbJJU0ZkXTBRHsG3r
"""

num_char = len(input("What is your name?"))
print("Your name has" + str(num_char) + "Character")

print(type(num_char))

prasad = len(input("What is your name"))

new_prasad = str(prasad)

print("Your name " + new_prasad + "character")

a = str(123)
print(type(a))

print(70 + float(100.75))
#print(str(70) + float(100.75)) error occured data type not match

#2.1 DATA TYPES  CODE CHALLENGE
two_digit_number = input("Type two numbers")
first_digit = int(two_digit_number[0])
second_digit = int(two_digit_number[1])
add = (first_digit) + (second_digit)
print(add)

print(3-5)
print(7 - 4)
print(3 * 2)
print(int(6)/int(3))
print(2 ** 3)

##PEMDAS L--> left TO R --> Right
#()
#**
#*
#/
#+
#-

print(3 * 3 + 3 / 3 - 3)

print(3 + 3 * 3 / 3 - 3) #my method

print(3 * (3 + 3) / 3 - 3) #ANOTHER METHOD

#2.2 BMI CALCULATOR
height = input("Enter Height")
weight = input("Enter Weight")
BMI = int(weight) / float(height) ** 2
bmi_as_int = int(BMI)
print(bmi_as_int)

#22 Number manipulation and F String in Python
print(8/3) #2.66666
print(int(8/3)) #2
print(round(8/3)) #3
print(round(8/3, 2)) #2.67
print(round(2.66666666666666666, 2)) #2.67
print(8//3) #integer only without converted integer
print(type(8//3)) #integer
result = 4/2 #2.0
result /= 2 #divide by 2 again
print(result)

#Use score
score = 0
score += 1

print(score)

#old method needed to Transafer into the string new method used here
#F-String
score = 0
height = 1.8
isWinning = True
print(f"Your score is {score}, your height is {height}, you are actually winning is {isWinning}")

#2.3 Your life in weeks challenges
age = input("What is your current age?")
new_age = int(age)
year_remains = 90- new_age
days = year_remains * 365
weeks = year_remains * 52
months = year_remains * 12
print(f"You have {days} days, {weeks} weeks and {months} months left")

#024 Tip Calculator

print("Welcome to the tip calculator")
bill = float(input("What was the total bill?"))
tip_percentage = int(input("What percentage tip would you like to give? 10, 12, or 15?"))
bill_split = int(input("How many people split the bill?"))

tip = bill * (tip_percentage/100)
actual_bill = bill + tip
split_bill = actual_bill / bill_split
round_off = round(split_bill, 2)
print(f"Each person should pay : {round_off}")

